version: '3.8'

services:
  samba:
    build: ./build
    image: samba
    restart: unless-stopped
    network_mode: host
    environment:
      INTERFACES: "${INTERFACES:?Setting INTERFACES is required}"
      NETBIOS_NAME: "${NETBIOS_NAME}"
      NETBIOS_ALIASES: "${NETBIOS_ALIASES}"
      WINS_SERVER: "${WINS_SERVER}"
